name: KICKS Scan

on:
  push:
    branches:
      - main  # Adjust the branch name as per your needs

jobs:
  scan-repositories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install KICS
        run: |
          curl -LsS https://get.kics.io | bash

      - name: Extract sub-repositories
        run: |
          python extract_subrepositories.py

      - name: Run KICKS scan
        uses: checkmarx/kics-github-action@master
        with:
          config-path: KICKS.yaml
