name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Trivy
        run: docker pull aquasec/trivy:0.19.2

      - name: Scan leading repository
        run: docker run --rm -v $(pwd):/workdir aquasec/trivy:0.19.2 image --format json -o trivy_results.json ${{ secrets.GITHUB_REPOSITORY }}
        id: leading_scan

      - name: Scan sub-repository portal-frontend
        run: docker run --rm -v $(pwd):/workdir aquasec/trivy:0.19.2 image --format json -o trivy_results.json ${{ fromJson(secrets.TRACTUSX_FILE).repositories[0].url }}

      - name: Scan sub-repository portal-frontend-registration
        run: docker run --rm -v $(pwd):/workdir aquasec/trivy:0.19.2 image --format json -o trivy_results.json ${{ fromJson(secrets.TRACTUSX_FILE).repositories[1].url }}

      - name: Scan sub-repository portal-assets
        run: docker run --rm -v $(pwd):/workdir aquasec/trivy:0.19.2 image --format json -o trivy_results.json ${{ fromJson(secrets.TRACTUSX_FILE).repositories[2].url }}

      - name: Scan sub-repository portal-backend
        run: docker run --rm -v $(pwd):/workdir aquasec/trivy:0.19.2 image --format json -o trivy_results.json ${{ fromJson(secrets.TRACTUSX_FILE).repositories[3].url }}

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy_results.json
          tool_name: 'Trivy Vulnerability Scanner'
          check_name: 'Trivy Scan'
          scan-type: "config"
          exit-code: "1"
          hide-progress: false
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
