name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Trivy
        run: docker pull aquasec/trivy:0.19.2

      - name: Extract sub-repository URLs
        run: |
          echo "${{ secrets.TRACTUSX_FILE }}" > .tractusx.base64
          base64 -d .tractusx.base64 > .tractusx
          sub_repos=$(awk '/url:/{getline; print}' .tractusx | awk '{print $2}')
          echo "::set-output name=sub_repos::$sub_repos"

      - name: Scan leading repository
        run: docker run --rm -v $(pwd):/workdir aquasec/trivy:0.19.2 image --format json -o trivy_results.json ${{ secrets.GITHUB_REPOSITORY }}
        id: leading_scan

      - name: Scan sub-repositories
        run: |
          for repository in ${{ steps.extract_urls.outputs.sub_repos }}; do
            docker run --rm -v $(pwd):/workdir aquasec/trivy:0.19.2 image --format json -o trivy_results.json $repository
          done

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy_results.json
          tool_name: 'Trivy Vulnerability Scanner'
          check_name: 'Trivy Scan'
          scan-type: "config"
          exit-code: "1"
          hide-progress: false
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
