name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@v0.6.0

      - name: Scan leading repository
        run: |
          trivy image --format json -o trivy_results.json ${{ secrets.GITHUB_REPOSITORY }}
        id: leading_scan

      - name: Scan sub-repositories
        run: |
          trivy image --format json -o trivy_results.json
            ${{ env.PORTAL_FRONTEND_REPO }}
            ${{ env.PORTAL_BACKEND_REPO }}
            ${{ env.PORTAL_ASSETS_REPO }}
            ${{ env.PORTAL_FRONTEND_REGISTRATION_REPO }}
        env:
          PORTAL_FRONTEND_REPO: ${{ fromJson(env.TRACTUSX_FILE).https://github.com/eclipse-tractusx/portal-frontend.url }}
          PORTAL_BACKEND_REPO: ${{ fromJson(env.TRACTUSX_FILE).https://github.com/eclipse-tractusx/portal-backend.url }}
          PORTAL_ASSETS_REPO: ${{ fromJson(env.TRACTUSX_FILE).https://github.com/eclipse-tractusx/portal-assets.url }}
          PORTAL_FRONTEND_REGISTRATION_REPO: ${{ fromJson(env.TRACTUSX_FILE).https://github.com/eclipse-tractusx/portal-frontend-registration.url }}
          TRACTUSX_FILE: ${{ secrets.TRACTUSX_FILE }}

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy_results.json
